openapi: 3.0.3
info:
  title: User API
  version: 1.1.0
paths:
  /users:
    get:
      operationId: getUsers
      summary: List all users with pagination
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          required: false
        - name: offset
          in: query
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
    post:
      operationId: createUser
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User created
  /users/{id}:
    get:
      operationId: getUserById
      summary: Get user by ID
      deprecated: true
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
        '404':
          description: User not found
  /users/{id}/details:
    get:
      operationId: getUserDetails
      summary: Get user details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User details
