package io.github.mohmk10.changeloghub.notification.formatter;

import io.github.mohmk10.changeloghub.core.model.*;
import io.github.mohmk10.changeloghub.notification.model.Notification;
import io.github.mohmk10.changeloghub.notification.util.NotificationConstants;

import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Formats messages as HTML emails.
 */
public class EmailMessageFormatter implements MessageFormatter {

    private static final DateTimeFormatter DATE_FORMAT =
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z")
            .withZone(ZoneId.systemDefault());

    @Override
    public String format(Notification notification) {
        if (notification.hasChangelog()) {
            return format(notification.getChangelog());
        }

        StringBuilder html = new StringBuilder();
        html.append(getHtmlHeader(notification.getTitle()));

        html.append("<div class=\"container\">");
        html.append("<div class=\"header\">")
            .append("<h1>").append(escapeHtml(notification.getTitle())).append("</h1>")
            .append("</div>");

        html.append("<div class=\"content\">");
        html.append("<p>").append(escapeHtml(notification.getMessage())).append("</p>");
        html.append("</div>");

        html.append("<div class=\"footer\">");
        html.append("<p>Sent by ChangelogHub at ")
            .append(DATE_FORMAT.format(notification.getCreatedAt()))
            .append("</p>");
        html.append("</div>");

        html.append("</div>");
        html.append(getHtmlFooter());

        return html.toString();
    }

    @Override
    public String format(Changelog changelog) {
        StringBuilder html = new StringBuilder();

        String title = "API Changes: " + (changelog.getApiName() != null ? changelog.getApiName() : "Unknown API");
        html.append(getHtmlHeader(title));

        html.append("<div class=\"container\">");

        // Header
        int breakingCount = changelog.getBreakingChanges().size();
        String headerClass = breakingCount > 0 ? "header breaking" : "header";

        html.append("<div class=\"").append(headerClass).append("\">");
        html.append("<h1>").append(escapeHtml(title)).append("</h1>");

        if (changelog.getFromVersion() != null && changelog.getToVersion() != null) {
            html.append("<p class=\"version\">Version ")
                .append(escapeHtml(changelog.getFromVersion()))
                .append(" → ")
                .append(escapeHtml(changelog.getToVersion()))
                .append("</p>");
        }
        html.append("</div>");

        // Summary
        int totalCount = changelog.getChanges().size();
        html.append("<div class=\"summary\">");
        html.append("<div class=\"stat\"><span class=\"number\">").append(totalCount).append("</span><span class=\"label\">Total Changes</span></div>");
        html.append("<div class=\"stat breaking\"><span class=\"number\">").append(breakingCount).append("</span><span class=\"label\">Breaking Changes</span></div>");
        html.append("</div>");

        // Breaking changes section
        List<BreakingChange> breakingChanges = changelog.getBreakingChanges();
        if (!breakingChanges.isEmpty()) {
            html.append("<div class=\"section breaking-section\">");
            html.append("<h2>⚠️ Breaking Changes</h2>");
            html.append("<ul>");
            for (BreakingChange bc : breakingChanges) {
                html.append("<li>");
                html.append("<strong>").append(escapeHtml(bc.getDescription())).append("</strong>");
                if (bc.getMigrationSuggestion() != null) {
                    html.append("<br><em class=\"migration\">Migration: ")
                        .append(escapeHtml(bc.getMigrationSuggestion()))
                        .append("</em>");
                }
                html.append("</li>");
            }
            html.append("</ul>");
            html.append("</div>");
        }

        // Other changes by severity
        List<Change> changes = changelog.getChanges();

        appendChangesSection(html, changes, Severity.DANGEROUS, "🟠 Dangerous Changes", "dangerous-section");
        appendChangesSection(html, changes, Severity.WARNING, "🟡 Warnings", "warning-section");
        appendChangesSection(html, changes, Severity.INFO, "🟢 Informational", "info-section");

        // Footer
        html.append("<div class=\"footer\">");
        html.append("<p>Generated by ChangelogHub at ")
            .append(DATE_FORMAT.format(Instant.now()))
            .append("</p>");
        html.append("</div>");

        html.append("</div>");
        html.append(getHtmlFooter());

        return html.toString();
    }

    private void appendChangesSection(StringBuilder html, List<Change> changes,
                                      Severity severity, String title, String cssClass) {
        List<Change> filtered = changes.stream()
            .filter(c -> c.getSeverity() == severity)
            .toList();

        if (filtered.isEmpty()) return;

        html.append("<div class=\"section ").append(cssClass).append("\">");
        html.append("<h2>").append(title).append("</h2>");
        html.append("<ul>");
        for (Change change : filtered) {
            html.append("<li>").append(escapeHtml(change.getDescription())).append("</li>");
        }
        html.append("</ul>");
        html.append("</div>");
    }

    private String getHtmlHeader(String title) {
        return """
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>%s</title>
                <style>
                    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }
                    .container { max-width: 600px; margin: 0 auto; background: white; }
                    .header { padding: 20px; background: #1a1a2e; color: white; }
                    .header.breaking { background: #dc3545; }
                    .header h1 { margin: 0; font-size: 24px; }
                    .header .version { margin: 10px 0 0; opacity: 0.9; }
                    .summary { display: flex; padding: 20px; background: #f8f9fa; }
                    .stat { flex: 1; text-align: center; }
                    .stat .number { display: block; font-size: 32px; font-weight: bold; }
                    .stat .label { font-size: 12px; color: #666; }
                    .stat.breaking .number { color: #dc3545; }
                    .section { padding: 20px; border-bottom: 1px solid #eee; }
                    .section h2 { margin: 0 0 15px; font-size: 18px; }
                    .section ul { margin: 0; padding-left: 20px; }
                    .section li { margin: 8px 0; }
                    .breaking-section { background: #fff5f5; }
                    .dangerous-section { background: #fff8f0; }
                    .warning-section { background: #fffef0; }
                    .info-section { background: #f0fff4; }
                    .migration { color: #666; font-size: 14px; }
                    .footer { padding: 20px; text-align: center; color: #999; font-size: 12px; background: #f8f9fa; }
                    .content { padding: 20px; }
                </style>
            </head>
            <body>
            """.formatted(escapeHtml(title));
    }

    private String getHtmlFooter() {
        return """
            </body>
            </html>
            """;
    }

    private String escapeHtml(String text) {
        if (text == null) return "";
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#39;");
    }

    @Override
    public String getContentType() {
        return NotificationConstants.CONTENT_TYPE_HTML;
    }
}
